"""Add labour and profit fields to Product

Revision ID: 2e1ed256c4af
Revises: 572a0651525f
Create Date: 2025-10-19 21:14:20.262244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e1ed256c4af'
down_revision = '572a0651525f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('labour_hours', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('hourly_rate', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('profit_margin', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('profit_margin')
        batch_op.drop_column('hourly_rate')
        batch_op.drop_column('labour_hours')

    # ### end Alembic commands ###
