"""Add EbayToken table for user auth

Revision ID: 572a0651525f
Revises: 7f89237e6b9e
Create Date: 2025-10-15 21:55:18.568057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '572a0651525f'
down_revision = '7f89237e6b9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ebay_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('refresh_token', sa.String(length=500), nullable=False),
    sa.Column('refresh_token_expiry', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ebay_token')
    # ### end Alembic commands ###
